sonar.projectKey=pedroct_gerador-de-hu_d683a3f3-d81b-4919-82cb-d5237effa7fa
sonar.qualitygate.wait=true

sonar.sources=gerar-backlog-azure-boards/scripts
sonar.tests=gerar-backlog-azure-boards/tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=https://sonar.pedroct.com.br
sonar.coverage.exclusions=**/tests/**
